spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  security:
#    user:
#      name: jerry
#      password: jerry123
#      roles: USER
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
#  datasource:
#    url: jdbc:postgresql://10.140.0.3:5432/postgresql
#    username: postgresql
#    password: postgrespassword
#    jpa:
#      show-sql: true
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080